# There should be a file called .github/workflows/frontend-cd.yaml in the root of the project.
# on every pull request against the main branch.
name: Miro's Terraform create infra
on:
    workflow_dispatch:
env:
  TERRAFORM_PATH: ./setup/terraform
  AWS_REGION: "eu-central-1"
jobs:
  create-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    defaults:
        run:
          working-directory: ${{ env.TERRAFORM_PATH }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

    #   # use role instead of user
    #   # https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/Github-runner-role #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"
      - run: terraform init

      - run: terraform apply --auto-approve